### ISSUE TITLE
Is there a flag to use GPU acceleration?

### ISSUE THREAD

**Issue by laurentopia** [Breakthrough/DVR-Scan#12]
OpenCV has a build using CUDA I think, so I was wondering if GPU acceleration flag existed in DVR-scan

**Comment by Breakthrough** [comment]
Unfortunately, the GPU module is not exposed in the OpenCV Python wrapper.

I do eventually want to rewrite the core of both DVR-Scan and PySceneDetect in C++ as a shared library, which would allow for this, but in the meantime, this is not possible with a pure-Python solution unfortunately.

Thank you for your submission.

**Comment by laurentopia** [comment]
Thanks,
I'm sifting through 8 hours of footage and it's taking a while, what optimization flags can I use?
The motion happens only in the lower third of the image, I could use a --region flag, couldn't find one though

**Comment by Breakthrough** [comment]
Hi @laurentopia;

Recently, there was a pull request merged which added the `-roi` flag which lets you set a region of interest.  This should provide a decent performance improvement.  See [my post here](https://github.com/Breakthrough/DVR-Scan/issues/3#issuecomment-507718860) for details.

Thank you!

**Comment by Breakthrough** [comment]
GPU acceleration should now be possible with the OpenCV Python bindings.  It may complicate building & distributing DVR-Scan a bit, but that may be a good solution for now to keep DVR-Scan written in Python but still provide significant performance improvements.  I don't have a timeline for this yet as I'm still having trouble compiling the module with CUDA support, but found [this resource](https://github.com/opencv/opencv-python#manual-builds) from the `opencv-python` package on pip which may be useful.

**Comment by laurentopia** [comment]
thank you, I'll keep that in mind the next time i need to sift through hours of footage

**Comment by Breakthrough** [comment]
Hey @laurentopia;  I'd like to keep this issue open, as I do want to investigate adding CUDA support.  Also note that the next release of DVR-Scan will include a faster algorithm, as per #48.  Thanks!

**Comment by CJPNActual** [comment]
Hi @Breakthrough,

I hope this is the correct place for this missive.  The TL;DR is that yes, indeed adding OpenCV CUDA support can, along with other important and significant optimisations, _massively_ improve throughput.  I.e. from 75fps to 1300fps.

One caveat:  I completely recreated the fundamentals of DVR-Scan in C# (fully managed and unsafe as required), as my Python skills are essentially non-existent, and I needed something significantly more performant as a matter of urgency. However some if not all the optimisations should carry across directly to the Python version.

Rather than detail the specifics in one giant wall of text, let me know if/when you're currently looking at this issue, and I would be more than happy to share the exact details and mechanics of the performance gains.

Best regards,

CJPN

Some screenies of DVR-Scan and the optimised setup working on the same source material with identical settings:

![DVRScan](https://user-images.githubusercontent.com/65857930/133097160-cb57e7fc-af8c-45af-99c2-5d4f0db68aa5.PNG)

----------------------------------------------------------------------------------------------------------------

![CJPNMotionDetect](https://user-images.githubusercontent.com/65857930/133097173-10bb01c8-0fb3-4f68-b48b-5a4cf631b068.PNG)

**Comment by Breakthrough** [comment]
Awesome result - would be glad to learn more about how you went about it.  I hope to eventually find something that targets both Nvidia and AMD GPUs, but even something CUDA based is better than nothing.

**Comment by CJPNActual** [comment]
> Awesome result - would be glad to learn more about how you went about it. I hope to eventually find something that targets both Nvidia and AMD GPUs, but even something CUDA based is better than nothing.

Indeed there are suggestions within OpenCV's docs - this being an imminent target of further research on this end - that utilising UMats as opposed to Mats automagically enables OpenCL processing with OpenCV choosing the fastest device available and falling back to CPU as required.

While CUDA is fun n'all that, it's proprietary nature does bring about a certain discomfort.  Particularly given current hardware shortages.

**Comment by CJPNActual** [comment]
Well.  OpenCL running on the GPU does indeed automagically work.  Performance is, however, nowhere close to the exact same algorithm operating explicitly in CUDA.  It appears as if OpenCV is uploading/downloading the UMat to/from the GPU between every processing step - i.e. GPU bus usage is higher with the OpenCL version running at 350FPS than the CUDA version running at 1300FPS - something that one can easily and explicitly prevent from occurring with OpenCV/CUDA.

Nevertheless, 350fps is an improvement over 75FPS, eh?  Further investigation required.

![CJPNMotionDetectOpenCL](https://user-images.githubusercontent.com/65857930/133422076-a82d235f-821e-40bb-b273-529b5fe94b30.PNG)

**Comment by CJPNActual** [comment]
The difference between CUDA and OpenCL isn't as bad as initially thought.  And is somewhat counterintuitive.

`4x 1080p

Running CUDA

Thread 1 @ frame 10622 (1920x1080) @ 307.44 FPS @ 0.64 Gpx/s.
Thread 2 @ frame 10667 (1920x1080) @ 321.28 FPS @ 0.67 Gpx/s.
Thread 3 @ frame 10243 (1920x1080) @ 303.71 FPS @ 0.63 Gpx/s.
Thread 4 @ frame 10951 (1920x1080) @ 334.74 FPS @ 0.69 Gpx/s.
Cumulative 1267.17 FPS.
Cumulative 2.63 Gpx/s.

------------------------------------------------------------------
4x 4K

Running CUDA

Thread 1 @ frame 1511 (3840x2560) @ 61.32 FPS @ 0.6 Gpx/s.
Thread 2 @ frame 1504 (3840x2560) @ 61.28 FPS @ 0.6 Gpx/s.
Thread 3 @ frame 1510 (3840x2560) @ 63 FPS @ 0.62 Gpx/s.
Thread 4 @ frame 1515 (3840x2560) @ 60.59 FPS @ 0.6 Gpx/s.
Cumulative 246.2 FPS.
Cumulative 2.42 Gpx/s.

------------------------------------------------------------------
4x 1080p

Running OpenCL

Thread 1 @ frame 2824 (1920x1080) @ 126.35 FPS @ 0.26 Gpx/s.
Thread 2 @ frame 2816 (1920x1080) @ 128.29 FPS @ 0.27 Gpx/s.
Thread 3 @ frame 2835 (1920x1080) @ 128.05 FPS @ 0.27 Gpx/s.
Thread 4 @ frame 2902 (1920x1080) @ 140.47 FPS @ 0.29 Gpx/s.
Cumulative 523.15 FPS.
Cumulative 1.08 Gpx/s.

------------------------------------------------------------------
4x 4K

Running OpenCL

Thread 1 @ frame 1716 (3840x2560) @ 34 FPS @ 0.33 Gpx/s.
Thread 2 @ frame 1721 (3840x2560) @ 34.27 FPS @ 0.34 Gpx/s.
Thread 3 @ frame 1725 (3840x2560) @ 34.6 FPS @ 0.34 Gpx/s.
Thread 4 @ frame 1707 (3840x2560) @ 35.72 FPS @ 0.35 Gpx/s.
Cumulative 138.59 FPS.
Cumulative 1.36 Gpx/s.
`

**Comment by Breakthrough** [comment]
@CJPNActual is there any source code you can share for your benchmarks?  Would love to integrate something like this into DVR-Scan, but I'm not that familiar with OpenCL.  Thanks!

**Comment by eded333** [comment]
> The difference between CUDA and OpenCL isn't as bad as initially thought. And is somewhat counterintuitive.
> 
> 4x 1080p
> 
> Running CUDA
> 
> Thread 1 @ frame 10622 (1920x1080) @ 307.44 FPS @ 0.64 Gpx/s. Thread 2 @ frame 10667 (1920x1080) @ 321.28 FPS @ 0.67 Gpx/s. Thread 3 @ frame 10243 (1920x1080) @ 303.71 FPS @ 0.63 Gpx/s. Thread 4 @ frame 10951 (1920x1080) @ 334.74 FPS @ 0.69 Gpx/s. Cumulative 1267.17 FPS. Cumulative 2.63 Gpx/s.
> 
> 4x 4K
> 
> Running CUDA
> 
> Thread 1 @ frame 1511 (3840x2560) @ 61.32 FPS @ 0.6 Gpx/s. Thread 2 @ frame 1504 (3840x2560) @ 61.28 FPS @ 0.6 Gpx/s. Thread 3 @ frame 1510 (3840x2560) @ 63 FPS @ 0.62 Gpx/s. Thread 4 @ frame 1515 (3840x2560) @ 60.59 FPS @ 0.6 Gpx/s. Cumulative 246.2 FPS. Cumulative 2.42 Gpx/s.
> 
> 4x 1080p
> 
> Running OpenCL
> 
> Thread 1 @ frame 2824 (1920x1080) @ 126.35 FPS @ 0.26 Gpx/s. Thread 2 @ frame 2816 (1920x1080) @ 128.29 FPS @ 0.27 Gpx/s. Thread 3 @ frame 2835 (1920x1080) @ 128.05 FPS @ 0.27 Gpx/s. Thread 4 @ frame 2902 (1920x1080) @ 140.47 FPS @ 0.29 Gpx/s. Cumulative 523.15 FPS. Cumulative 1.08 Gpx/s.
> 
> 4x 4K
> 
> Running OpenCL
> 
> Thread 1 @ frame 1716 (3840x2560) @ 34 FPS @ 0.33 Gpx/s. Thread 2 @ frame 1721 (3840x2560) @ 34.27 FPS @ 0.34 Gpx/s. Thread 3 @ frame 1725 (3840x2560) @ 34.6 FPS @ 0.34 Gpx/s. Thread 4 @ frame 1707 (3840x2560) @ 35.72 FPS @ 0.35 Gpx/s. Cumulative 138.59 FPS. Cumulative 1.36 Gpx/s.

This seems extremely promising both for cuda and opencl. Any chance you can share the source code?

**Comment by CJPNActual** [comment]
Copied from recent email:

I rewrote the entire concept in C#, with sections of unsafe (C++ style) code for added memory voodoo where using FFMPEG for video decoding is concerned, so am not certain it translates directly to Python with a source-share...

However, getting the base-concept to run on CUDA or OpenCL is as simple as redefining some of the OpenCV textures as "graphics card resident" and then calling the same functions on them with the now GFX-resident textures/bitmaps as arguments as opposed to the "CPU-resident" ones.  OpenCV will deal with all of the difficult copy-to-gfx-card stuff internally.  The code on your end should look almost identical with minor changes as mentioned.

Does that make sense?

**Comment by Breakthrough** [comment]
Yes, totally.  Could you point me to any code samples for that in OpenCV 4? (C++ is fine)  I am considering rewriting DVR-Scan in Rust for the next version which should support most of the C++ style stuff.  Thanks!

**Comment by ijutta** [comment]
Is there any way to run dvr-scan with GPU acceleration? Sorry, I am totally n00b and I only can start it on Windows or Linux, where it could be possible to increase power with GPU.

I would be very interested in helping in developing/testing dvr-scan, but I totally don't know where to start...

Best regards,
Adam

**Comment by Breakthrough** [comment]
@ijutta it's fairly straight forward to modify the `scan_motion` function to support the OpenCV CUDA module.  For the most part, there are drop-in replacements for the CPU bound versions.

The main reason I haven't pursued this change yet is, I haven't had time to actually compile + test the OpenCV Python module with all the required dependencies for CUDA development, nor is there a binary package anyone distributes.  The work here is less so doing it just one time, and more creating an **automated** way of downloading all dependencies, building the module, and actually testing DVR-Scan against it.  I don't have any access to build systems that are GPU-enabled (if anyone knows any free ones let me know!).

The other reason is, I want to look into how to best support OpenCL/Vulkan, not just CUDA, and I also need to look into any potential licensing issues with redistributing a custom built OpenCV binary with CUDA support.

That being said, the next release of DVR-Scan will include multithreading to improve performance.  It will still be slower than using a GPU for calculation, but should be at least 50% faster than the current version.  Once that's done, I'll pick this up for v1.6 and at least try to support versions of OpenCV that are compiled with CUDA support at minimum.

**Comment by Breakthrough** [comment]
@ijutta interestingly enough, I just happened to find someone distributing prebuilts for Windows:
https://jamesbowley.co.uk/downloads/

I'll see how difficult it is to mock something up to at least get a decent performance comparison and get back to you.  I still need to see how to best support both CPU + GPU scanning in the long run, but will keep this in mind during the v1.5 refactor to make that an explicit goal.

**Comment by Breakthrough** [comment]
I actually made some progress on getting this working!  You can download and install an experimental version to test out:  [dvr_scan-1.5.dev0-py3-none-any.whl.zip](https://github.com/Breakthrough/DVR-Scan/files/8905268/dvr_scan-1.5.dev0-py3-none-any.whl.zip) (extract + `pip install` the .whl file)

Once installed, you can use the `-b mog_cuda` to enable CUDA processing, e.g.:

    dvr-scan -i video.mp4 -b mog_cuda -so

I would recommend comparing performance in scan-only mode (`-so`) as currently video encoding is not done in parallel, but this is being worked on as well.  This roughly doubles processing speed on my machine.

On CPU, I get around 55 FPS when scanning for motion events, and 35 FPS when processing an event.  With CUDA, I get around 95 during scanning, which drops down to ~55 FPS when processing.  Again these numbers should improve once the processing/encoding is done in parallel with the motion scanning.

If folks could help out by testing this, that would be fantastic.

**Comment by CJPNActual** [comment]
(((Strong disclaimer! I possess virtually no Python expertise.)))

Running the new experimental build immediately complains that:

`dvr-scan.exe: error: argument -b/--bg-subtractor: invalid choice: mog_cuda (valid settings for TYPE are: 'mog', 'cnt')`

**Comment by CJPNActual** [comment]
Apologies.  Didn't see the edits until now.  While, in my tests, OpenCL performs at ~50% of CUDA, obviously not everybody possesses and Nvidia card.

> Edit2: And sorry do you have examples of that for OpenCL? I assumed OpenCV only supported CUDA for certain things.

It's been a while since I tested OpenCL, yet my observations - at least using Emgu.CV, the .NET wrapper - is that rather than explicitly creating an OpenCL pipeline as one would with CUDA, one instead instructs OpenCV as a whole to utilise OpenCL via its "native" interface thusly:

```
CvInvoke.UseOpenCL = true;
CvInvoke.UseOptimized = true;
```

Subsequently one calls one's pipeline via the native interface, with the exception of the background subtractor which one calls normally via it's member .Apply() function.  I believe there may be one caveat in that certain Mats need to be UMat, but otherwise it's relatively easy to port from CPU-only code.  Easier than CUDA, one might posit.

**Comment by CJPNActual** [comment]
Other optimisations worth noting:

1.  The general architecture is as follows:

```
-------------------------------n x Processing Container threads---------------------------------------------------------			
-	Decode Thread -> n-frame FIFO buffer -> Processing Thread -> n-frame FIFO buffer -> Optional Encode & ffmpeg cleanup Thread
- 
-   ffmpeg_frame created ---------------no YUV to RGB to YUV conversion------------------------> ffmpeg_frame freed.   
------------------------------------------------------------------------------------------------------------------------
```

2.  One generally require n x 3 to equal number of CPU cores in order to properly saturate GPU.

3. GPU driver/task manager lie.  They report GPU activity **at the GPU's current clock speed**.  Due to unknown bottlenecks multiple concurrent processing containers are required in order to push GPU to max frequency.

4. While a royal pain the the backside compared to using OpenCV's own video decoding/encoding functions, using ffmpeg and properly managing frame lifecycle not only avoids unnecessary YUV -> RGB -> Monochrome conversions and significantly conserves RAM bandwidth, but is also much more likely to be performance-optimised when compared to OpenCV, whose model tends towards ease of use.

5.  Indeed, ffmpeg is capable of a "fast-copy", without encoding, of video given timestamps of a source.  One needs to be able to seek to an I-frame for this to work flawlessly, yet doing so almost completely mitigates the encoding overhead.  Still a work in progress on this end as ffmpeg is difficult and often painful.  50% compete on this end.

**Comment by Breakthrough** [comment]
@CJPNActual are you sure you uninstalled any existing versions of DVR-Scan before installing the experimental version?  What do you see if you run `dvr-scan --version`?  This certainly has much more opportunities for optimization, so thanks for suggesting some ideas.

The main focus for v1.5 will be to implement a multithreaded model similar to what you've suggested, and offload video encoding to ffmpeg in a subprocess (having DVR-Scan output a list of cuts and video filters to overlay timestamps/bounding boxes where required).  It feels like this is pushing the boundaries of an application written in Python though, which is why I'd like to investigate possibly rewriting the project in Rust.  That would also allow tighter integration with the various C/C++ libraries and allow better control over memory management, threading/locking, and integration with the ffmpeg API.

**Comment by Breakthrough** [comment]
I've also uploaded an experimental .exe build for 64-bit Windows systems for Nvidia GTX 900-series and above GPUs which [you can grab here](https://github.com/Breakthrough/DVR-Scan/releases/download/v1.4.1/DVR-Scan-1.5.dev0-win64-portable-CUDA.zip).  Make sure you have CUDA support enabled with your current GPU driver, e.g. when clicking System Information in the Nvidia Control Panel, you should see NVCUDA64.dll under the Components tab, e.g.:

![image](https://user-images.githubusercontent.com/125316/173932599-3e64cbec-f5f7-4db7-b680-604c626ed3f2.png)

Feedback on both this and the experimental Python version above is most welcome.

**Comment by Breakthrough** [comment]
Have the multithreaded version ready for testing in the v1.5 branch, just need to cleanup a few things before making another release candidate.  From the experimental version above though, now I'm getting closer to 150 FPS from 100 FPS before when using CUDA mode.  In CPU mode, using MOG, I can now get close to real-time full frame processing (~60FPS).

This opens up a lot of doors now, but for the time being this is as much optimization as I can commit to for v1.5.  Of course, if there's any optimizations folks might find or be able to help out with, I would be more than happy to include those in v1.5.  Now that there's GPU support in place, once 1.5 is released, I may close this issue and create a new one specifically to focus on optimization opportunities (including those brought up in this issue).

**Comment by CJPNActual** [comment]
@Breakthrough Sorry for being a pedant, however given that we're currently and collectively engaged in performance optimisation and/or research, could we speak in Gigapixels/second or some such, as it removes input resolution and framerate from the equation.  Also worth mentioning one's hardware setup, as I'm relatively certain a Raspberry PI performs differently to... :)

**Comment by CJPNActual** [comment]
F.ex. my research UI:
![Motion Detect Pigapixels](https://user-images.githubusercontent.com/65857930/175311132-9784d7e3-5f88-4fde-9118-af56ea2fe21e.png)

**Comment by Breakthrough** [comment]
v1.5 has officially been released, looking forward to any feedback for the new CUDA builds.  Will close this issue, but feel free to create new issues or discussions if any issues crop up.  As mentioned previously there are likely some areas of improvement regarding performance still, so happy to have any new ideas as well.  Will leave this issue pinned for the meantime.

**Comment by sundeepgoel72** [comment]
If there are any particular PoCs you want to conduct on the performance side using CUDA, or look at some sections of code for optimizations - give me a shout.

currently my 750Ti only around 5-10% utilised while processing large files using MOG2_CUDA, so i suspect more could be done. Out for two weeks, but will be happy to give it a bash once back.
