### ISSUE TITLE
Enhance the detection of small objects - for astronomy use - option to remove kernel?

### ISSUE THREAD

**Issue by AlverGant** [Breakthrough/DVR-Scan#123]
First of all congratulations for DVR-Scan! It is relatively simple to use, fast and do the job.

I am an amateur astronomer and my interests are tracking of satellites and meteors, for that I setup a sensitive Sony IMX 291 camera looking at the sky and would be glad if DVR-Scan could detect those objects but they are relatively small, a few pixels wide and I got the impression that the noise reduction kernel is interfering with the detection so if it's the case I would like to request the option to remove the kernel.

Here is a sample of a video with one of this kind of objects, a plane. It is small and relatively slow but has high contrast and I am having issues detecting it,
https://drive.google.com/file/d/1wGob2ziWgbaHND8MPjYYexNo8D5l4v97/view?usp=sharing
I am using the following parameters:
dvr-scan -i plane.mp4 -bb -roi 253,6 1244,998 -t 0.05 -l 2 -k 3 -b MOG2

I am not so concerned regarding some false positives as long as detection of these objects work. Any suggestions on how to improve the detection are welcome.

Thank you and best regards

**Comment by Breakthrough** [comment]
Hi @AlverGant;

Sorry for the delay in getting back to you - thank you so much for the sample.  I see how the noise reduction would mess up some very small objects like that, and am more than happy to add an option to disable it.

If you're comfortable modifying the code I can point you in the right direction, otherwise I'll make sure to include this fix in the next release of DVR-Scan.  Thanks for the report!

**Comment by AlverGant** [comment]
Thanks @Breakthrough !! 
I will wait for the new release!

**Comment by Breakthrough** [comment]
_Fix will be included in v1.6 release, thanks!_
