### ISSUE TITLE
Please document how to get cuda working

### ISSUE THREAD

**Issue by reubenfirmin** [Breakthrough/DVR-Scan#129]
**Description of Problem & Solution**
When I try to run with cuda, I get an error saying that I need to install a version of cv2 with support for cuda. How do I do that? Can you provide setup instructions?

Thanks

**Comment by Breakthrough** [comment]
See #12 for some background on this.  Unfortunately I cannot provide instructions for building + installing OpenCV with GPU support, you will need to either download a pre-built one or follow a tutorial.  Thank you for your understanding.

**Comment by subbyte** [comment]
If you are using archlinux, now you can get it simply:
```
sudo pacman -S python-opencv-cuda
```

For other Linux distribution, you may need to compile OpenCV with CUDA support like [this article](https://medium.com/@amosstaileyyoung/build-opencv-with-dnn-and-cuda-for-gpu-accelerated-face-detection-27a3cdc7e9ce).

Some notes:
1. You need `opencv_contrib` besides the main `opencv` repo, since the background subtraction module for CUDA is in the contrib repo.
2. Use `-j` in cmake to vastly speed up compilation. The command I used: `cmake --build . -j 10`, which speed up hours of building time to 20min.
3. You may need to export `CUDAHOSTCXX=/usr/bin/g++-13` since CUDA does not support very new gcc/g++, e.g., gcc 14 in archlinux.
4. Use configuration arguments like `ARCH` and `gencode` to only generate code for your GPU to speed up compilation. Check the GPU gencode from [this article](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/).
