### ISSUE TITLE
Performace of analyzing

### ISSUE THREAD

**Issue by myscho15** [Breakthrough/DVR-Scan#51]
Hay, first i love you program!

I use your software for analyzing videos from security cameras. (Rsolutions Full HD - 15/25fps, hd 15fps)

I have imac 27 inch (2017) 3,8Ghz intel core i5 with 4 cores. And notebook with similar procesor little bit slower.

When software analyzing HD with 15fps - making, speed of analyzing is 160-170 fps, but when is Full HD analyzed with 15 fps - ist about 65 fps and with 25fps is 35-40fps performance.

Please help me with this, i want better perrformace, wich kind of Processor i need to buy (yes i need whole new pc) but with what kind of processor (AMD Intel) become i better performance. What is important - number of cores, or speed, or cache? I want to buy new PC direct for this software, but i dont know what is important, please help me with wich one choose - 

I am biggest noob to programming and to in computer.

Thank you verry much for your answer

**Comment by Breakthrough** [comment]
Hi @myscho15;

Part of the problem is actually with how DVR-Scan is written and distributed.  The biggest issue is that it's not possible (yet) to enable GPU acceleration.  You might also get better performance by compiling the `opencv-python` module manually, enabling all of the relevant options to ensure it's optimized (there are instructions [here](https://github.com/opencv/opencv-python/#manual-builds) for doing so).

Other than that, the current bottleneck is likely CPU clock speed and memory bandwidth.  Since there's no parallelization, number of cores doesn't matter either.  I don't believe the underlying libraries I'm using support parallel implementations either, however, they do have GPU support.  Again though, DVR-Scan doesn't support this, but when it does, a GPU would definitely help.

Hope this helps!

**Comment by Breakthrough** [comment]
Closing as duplicate of #12.

**Comment by Breakthrough** [comment]
You might also want to see #48 - there are some newer background subtraction algorithms OpenCV provides which *can* use multiple CPU cores.  As those are included in the binaries already, I might be able to enable that by adding a flag to the command line to switch between different background subtraction algorithms.

Work for multiple CPU cores will be tracked in #48, and GPU support will be tracked in #12.

**Comment by Breakthrough** [comment]
Hey @myscho15;

I actually made some progress in #48!  The next version of DVR-Scan will include a faster way of scanning by specifying `-b CNT`.  Keep an eye out for DVR-Scan v1.3 when it will be included.  On my system, it improves my scanning performance from 90 FPS to 125 FPS.

Thanks!

**Comment by myscho15** [comment]
Hallo,

i thank you verry much for your software, sponsoring is the smallest thing to say you THANK YOU! I will check you updates of DVR-SCAN.

**Comment by myscho15** [comment]
Hay,

Is no problem and it is the smallest thing that i make for you! Is only 5euro per month, but your work on Your software is the valuest thing. 

I mean that lower performace is because i have older PC. I mean when i buy new PC or MAC will better, but i dont know.

My pc knowlenge is verry poor. I mean when i have more cores in cpu will be better or new M1 MAC will be better i dont know how your software is working, i mean better cpu better oerformance. 

But is big help your software also with current performance. But i will wait for new version

Thank you verry verry verry much for you hard work.

Sorry for my poor english and poor PC MAC knowlenge :-(

Have a Nice Day.

Michal

**Comment by Breakthrough** [comment]
Hey @myscho15;

With DVR-Scan v1.3, you can specify `-b CNT` and it will use the new parallelized background subtractor!  It should give you some better performance when scanning.

Feel free to provide any feedback here or in #48.  Thanks again! :)
